[versions]
agp = "8.10.1"
kotlin = "2.0.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
composeBom = "2024.09.00"

materials3 = "1.3.1"
hilt-android = "2.51.1"
hilt-navigation-compose = "1.2.0"
kotlinx-serialization-json = "1.7.3"
navigation-compose = "2.8.5"
retrofit="2.11.0"
ksp = "2.0.0-1.0.21"
room-runtime = "2.5.0"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref="materials3" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime"}
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-room-compiler = {module = "androidx.room:room-compiler", version.ref = "room-runtime"}

hilt-android = {module = "com.google.dagger:hilt-android", version.ref = "hilt-android"}
hilt-android-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android"}

retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
converter-gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}

kotlinx-serialization-json = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json"}
androidx-navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref ="navigation-compose"}

androidx-hilt-compiler = {module = "androidx.hilt:hilt-compiler", version.ref = "hilt-navigation-compose"}
androidx-hilt-navigation-compose = {module = "androidx.hilt:hilt-navigation-compose", version.ref="hilt-navigation-compose"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHilt = {id = "com.google.dagger.hilt.android", version.ref = "hilt-android"}
compose-compiler = {id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
kspAndroid = { id = "com.google.devtools.ksp", version.ref = "ksp"}


